/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define ALIAS_BASE_M4		(0x22000000ul)
#define SRAM_BITBASE_M4		(0x20000000ul)
#define ALIAS_ADDR_M4(x, y)		(ALIAS_BASE_M4+(32*(x - SRAM_BITBASE_M4))+(y*4))

#if !defined(__SOFT_FP__) && defined(__ARM_FP) && 0
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void initialise_monitor_handles(void);

int main(void)
{

	uint8_t volatile *pSRAM = (uint8_t *)(0x20000200);
	*pSRAM = 0x0; //Clear the memory cell
	initialise_monitor_handles();
	printf("Value at %p is: %d\n", pSRAM, *pSRAM);
	uint32_t pSRAM_addr = (uint32_t)pSRAM;
	uint8_t volatile *pSRAM_ALIAS;
	/* Loop forever */
	for(volatile int i = 0; i < 8; i++){
		pSRAM_ALIAS = (uint8_t *)(ALIAS_ADDR_M4(pSRAM_addr, i));
		*pSRAM_ALIAS = 1;
		initialise_monitor_handles();
		printf("Value at %p is: %d\n", pSRAM, *pSRAM);

	}

	for(;;);
}
